apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ha-1
  labels:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: postgresql-ha  
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /srv/k8s_volume/psql_1
    server: 10.5.0.31
