---

  - include_vars: "{{ playbook_dir }}/config.yml"      
  - include_vars: "main.yml"      

  - name: Delete hosts
    file: 
      path: hosts
      state: absent
  
  - name: Create hosts
    file:
      path: hosts
      state: touch  
      mode: '0744'

  - name: Add entries to the hosts
    lineinfile:
      path: hosts
      line: |
        [{{ item.name }}]
        {{ item.ip }}
    with_items:
      "{{ hypervisors }}"
    
  - name: Add master nodes to the hosts 1
    lineinfile:
      path: hosts
      line: '[master]'

  - name: Add master nodes to the hosts 2
    lineinfile:
      path: hosts
      line: "{{ item.ip }}"
    with_items:
      "{{ nodes.master }}"
          
  - name: Add worker nodes to the hosts 1
    lineinfile:
      path: hosts
      line: '[worker]'

  - name: Add worker nodes to the hosts 2
    lineinfile:
      path: hosts
      line: "{{ item.ip }}"
    with_items:
      "{{ nodes.worker }}"
  
  - name: Add masters individually
    lineinfile:
      path: hosts
      line: |
        [{{item.name}}]
        {{ item.ip }}

    with_items:
      "{{ nodes.master }}"

  - name: Define first master
    lineinfile:
      path: hosts
      line: |
        [FIRST_MASTER]
        {{ nodes.master[0].ip }}
  
  - name: Define other master nodes
    lineinfile:
      path: hosts
      line: |
        [OTHER_MASTERS]
        {{ nodes.master[1].ip }}
        {{ nodes.master[2].ip }}


  - name: Add workers individually
    lineinfile:
      path: hosts
      line: |
        [{{item.name}}]
        {{ item.ip }}

    with_items:
      "{{ nodes.worker }}"
  
  - name: Add HIP ip to the inventory
    lineinfile:
      path: hosts
      line: |
        [{{item.name}}]
        {{ item.ip }}

    with_items:
        "{{ cluster.resources }}"

  - name: Refresh inventory 
    meta: refresh_inventory

  





